version: "3"

services:
  myAppName:
    build: .
    container_name: myAppName
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${REACT_NATIVE_PACKAGER_HOSTNAME}
    volumes:
      - ../../myAppName:/var/myAppName
    ports:
      - 19000:19000
      - 19001:19001
      - 8081:8081