version: "3"

services:
  testdo:
    build: .
    container_name: testdo
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${REACT_NATIVE_PACKAGER_HOSTNAME}
    volumes:
      - ../../testdo:/var/testdo
    ports:
      - 19000:19000
      - 19001:19001
      - 8081:8081