version: "3"

services:
  app:
    build: .
    container_name: myApp
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${REACT_NATIVE_PACKAGER_HOSTNAME}
    volumes:
      - ../../boilerplate-react-native-expo:/var/boilerplate-react-native-expo
    ports:
      - 19000:19000
      - 19001:19001
      - 8081:8081